# Spring
spring:
  profiles:
    active: dev,default

  application:
    name: ioften

info:
  app:
    name: ${spring.application.name}
    profile: ${spring.profiles.active}
    version: "0.0.1"
    description: "ioften startup module"
    spring-boot-version: "0.0.1"
    api-doc-wiki: http://127.0.0.1:${server.port}/swagger-ui.html