# Spring
spring:
  profiles:
    active: dev

  application:
    name: ytdev.org

springfox:
  documentation:
    swagger.v2.path: /

info:
  app:
    name: ${spring.application.name}
    profile: ${spring.profiles.active}
    version: "@project.version@"
    description: "@project.description@"
    spring-boot-version: "@project.parent.version@"
    api-doc-wiki: http://127.0.0.1:${server.port}/swagger-ui.html