# Spring
spring:
  profiles:
    active: dev

  application:
    name: ytdev.org

info:
  app:
    name: "boot"
#    name: ${spring.application.name}
    profile: ${spring.profiles.active}
    version: "0.0.1"
    description: "redis mysql spring spring-mvc spring-boot mybatis-spring restful-api"
    spring-boot-version: "0.0.1"
    api-doc-wiki: http://127.0.0.1:${server.port}/swagger-ui.html