spring:
  rabbitmq: # MQ
    port: 5672
    host: rabbitmq.ytdev.org
    username: dev
    password: 123456
    virtual-host: /dev
    publisher-returns: true # 开启发送失败退回
    publisher-confirms: true # 开启发送消息确认
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: MANUAL # 开启手动ACK
      simple:
        acknowledge-mode: MANUAL # 开启手动ACK
